### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by DavertMik** [kaflan/backend_part_of_litle_test_case#1]
https://github.com/kaflan/backend_part_of_litle_test_case/blob/29e163fa1bf1185e9cf96b722c5b17b518495c67/src/app.service.ts#L22

Почему return any? если возвращается промис

**Comment by DavertMik** [comment]
Пропиши нормальный тип и должно быть ок

И да `getPlanetesUrls` скорее всего должно быть `getPlanetsByUrl()`

**Comment by kaflan** [comment]
fix
